name: ${pom.name}
version: ${pom.version}
description: ${pom.description}
website: ${pom.url}
author: Lightnew
main: fr.lightnew.CustomShop
commands:
  shop:
    permission: customshop.command.shop
  eco:
    permission: customshop.command.eco